In [1]:
from   ctypes import *
from    scipy import sparse

import  numpy as np
import  random

# treat this as a library call and put it here

keith_module    = "keith_module.so"
keith_functions = CDLL(keith_module)
keith_mutate    = keith_functions.keith_mutate()


In [2]:
'''# speed comparison of four approaches    '''
'''    # base_mutate native python libraries        '''
'''    # pygad_mutate specialist libraries and two for loops'''
'''    # vector_mutate special libraries and aggressive vectorisation'''
'''    # keith_mutate modular call from bespoke C function in local library '''
'''                                                                                 '''
'''# further optimisations maybe possible with the four approaches                          '''
'''# note that mutate request internally casts the numpy population into a list of lists            '''

'# note that mutate request internally casts the numpy population into a list of lists            '

In [4]:
class MutateRequest:
    def __init__(self, population):
        
        # fairer to start with the native list object and require modules to promote to array
        # than have "naive" modules demoting ndarrays back down to lists
        number_of_mutations = get_number_of_mutations()
        self.population     = population
        self.population     = [list(algo) for algo in population] # see explanation of choice of list not ndarray
        self.rows_algos     = len(population)
        self.columns_genes  = len(population[0])
        self.number_of_mutations = number_of_mutations

class TellObject:
    def __init__(self, population, base_mutants, keith_mutants, pygad_mutants, vector_mutants):
        self.population     = population
        self.base_mutants   = base_mutants
        self.keith_mutants  = keith_mutants        
        self.pygad_mutants  = pygad_mutants
        self.vector_mutants = vector_mutants
        
def get_random_mutation_min_val():
    return -2

def get_random_mutation_max_val():
    return 2
        
def tell(tell_object):
    print('\noriginal population\n', np.around(np.asarray(tell_object.population), decimals=4))
    print('\nmutation by base libraries')
    for i in range(len(tell_object.base_mutants)):
          print(np.around(np.asarray(tell_object.base_mutants[i]),decimals=4))
    print('\nmutation by aggressively vectorised scipy\n', np.around(np.asarray(tell_object.vector_mutants), decimals=4))
    print('\nmutation by pygad function\n', np.around(np.asarray(tell_object.pygad_mutants), decimals=4))
    print('\nmutation by bespoke C function\n', np.around(np.asarray(tell_object.keith_mutants), decimals=4))

def get_number_of_mutations():
    number_of_mutations = 1
    return number_of_mutations

def build_population():
    low         = -1
    high        =  1
    cohort_size = (4, 8) #  rows_algos, columns_genes
    population  = np.random.uniform(low, high, size=cohort_size)
    return population

In [5]:
def base_mutate(mutate_request):
    '''only uses naive base library - math, itertools, random etc are allowed'''
    base_mutants        = mutate_request.population
    number_of_mutations = mutate_request.number_of_mutations
    rows_algos          = mutate_request.rows_algos
    columns_genes       = mutate_request.columns_genes

    for algo in base_mutants:
        for mutation in range(number_of_mutations):
            random_place    = random.randrange(columns_genes)
            starting_gene   = algo[random_place]
            a_float         = random.random()
            algo.pop(random_place)
            mutant_gene     = starting_gene + a_float
            algo.insert(random_place, mutant_gene)
    return base_mutants

In [6]:
def keith_mutate(mutate_request):
    keith_mutants = np.copy(mutate_request.population)
    keith_mutants[0][0] = 3.1415926535
    return keith_mutants

'''
# keith mutate
'''

def test_keith_mutate():
    number_of_mutations   = get_number_of_mutations()
    population            = build_population()
    mutate_request        = MutateRequest(population)
    mutants               = keith_mutate(mutate_request)
    max_parity_sum        = population.shape[0] * population.shape[1]
    rows_algos            = mutate_request.rows_algos
    
    #form
    assert isinstance(mutants,      np.ndarray),  'Error: should be an np array'
    assert isinstance(mutants[0],   np.ndarray),  'Error: should be an np array'
    assert isinstance(mutants[0][0],float),       'Error: should be a float'
    
    #content
    flat_population = list(np.ravel(np.asarray(population)))
    flat_mutants    = list(np.ravel(np.asarray(mutants)))
    both            = zip(flat_population, flat_mutants)
    parity_check    = sum([int(x[0]==x[1]) for x in both])
    if number_of_mutations > 0:
        assert parity_check <= max_parity_sum-rows_algos, 'Error: there should be at least one difference per algo'
    assert parity_check > 0, 'Error: they should not be completely different'
    print('pass')
    
#test_keith_mutate()

In [7]:
def pygad_mutate(mutate_request):
    # 1. removed dependency on gene_type
    # 2. all modules for these time trials start with a list because they refer to the MutateRequest
    #    and the mutate reqeust offers a list as the most basic thing
    #    so if this module seems handicapped by e.g. the need to retype offspring as an array then
    #    people are welcome to change the interface, but it just passes that handicap elsewhere

    offspring                = np.asarray(mutate_request.population)
    num_genes                = mutate_request.columns_genes
    mutation_num_genes       = mutate_request.number_of_mutations
    random_mutation_min_val  = get_random_mutation_min_val()
    random_mutation_max_val  = get_random_mutation_max_val()
    
    for offspring_idx in range(offspring.shape[0]):
        mutation_indices = np.array(random.sample(range(0, num_genes), mutation_num_genes))
        for gene_idx in mutation_indices:
            random_value = np.random.uniform(low=random_mutation_min_val, 
                                            high=random_mutation_max_val, 
                                            size=1)
            offspring[offspring_idx, gene_idx] = offspring[offspring_idx, gene_idx] + random_value
    return offspring

In [8]:
def vector_mutate(mutate_request):

    population          = np.asarray(mutate_request.population)
    number_of_mutations = mutate_request.number_of_mutations
    all_loci            = mutate_request.rows_algos * mutate_request.columns_genes
    mutation_rate       = number_of_mutations/mutate_request.columns_genes
    
    mutation_matrix = sparse.random(population.shape[0], population.shape[1], density=mutation_rate)
    pre_mutants     = np.copy(population)
    mutants         = np.add(pre_mutants, mutation_matrix.todense())
    return mutants

In [9]:
if __name__ == '__main__':
    
    population          = build_population()
    mutate_request      = MutateRequest(population)
    
    base_mutants        =  base_mutate(mutate_request)
    keith_mutants       = keith_mutate(mutate_request)
    pygad_mutants       = pygad_mutate(mutate_request)
    vector_mutants      = vector_mutate(mutate_request)
    
    that_which_to_tell = TellObject(population, base_mutants, keith_mutants, pygad_mutants, vector_mutants)
    tell(that_which_to_tell)
    


original population
 [[ 0.4781 -0.8581 -0.6086 -0.3427 -0.8429  0.8887  0.8015  0.5368]
 [ 0.5626  0.189   0.3113 -0.0114  0.3944 -0.4523 -0.4248  0.5202]
 [ 0.067  -0.7735  0.4036 -0.4243 -0.4277  0.8203 -0.1115 -0.357 ]
 [-0.7021 -0.0627 -0.8608 -0.7541  0.0012  0.3474  0.3003 -0.7169]]

mutation by base libraries
[ 0.4781 -0.8581 -0.3304 -0.3427 -0.8429  0.8887  0.8015  0.5368]
[ 0.5626  0.189   0.3113 -0.0114  0.3944  0.0619 -0.4248  0.5202]
[ 0.067  -0.7735  1.2227 -0.4243 -0.4277  0.8203 -0.1115 -0.357 ]
[-0.7021 -0.0627 -0.8608 -0.7541  0.9882  0.3474  0.3003 -0.7169]

mutation by aggressively vectorised scipy
 [[ 0.4781 -0.8581  0.3941 -0.3427 -0.8429  0.8887  0.8015  0.5368]
 [ 0.5626  0.189   0.3113 -0.0114  0.3944  0.0619 -0.4248  0.5202]
 [ 0.0742 -0.1385  1.2227 -0.4243 -0.4277  0.8203 -0.1115 -0.357 ]
 [-0.7021 -0.0627 -0.8608 -0.7541  0.9882  0.3474  0.6747 -0.7169]]

mutation by pygad function
 [[ 0.4781 -2.4756 -0.3304 -0.3427 -0.8429  0.8887  0.8015  0.5368]
 [ 0.562

In [10]:
'''
# build population
'''

def test_build_population():
    population = build_population()
    assert isinstance(population,       np.ndarray),    'Error: should be array of arrays'
    assert isinstance(population[0],    np.ndarray),    'Error: should be an array'
    assert isinstance(population[0][0], np.float64),    'Error: should be a float'
    print('pass')

In [11]:
'''
# base mutate
'''    

def test_base_mutate():
    number_of_mutations   = get_number_of_mutations()
    population            = build_population()
    mutate_request        = MutateRequest(population)
    mutants               = base_mutate(mutate_request)
    max_parity_sum        = population.shape[0] * population.shape[1]
    rows_algos            = mutate_request.rows_algos
    
    #form
    assert isinstance(mutants,      list),  'Error: should be a list'
    assert isinstance(mutants[0],   list),  'Error: should be a list'
    assert isinstance(mutants[0][0],float), 'Error: should be a float'
    
    #content
    flat_population = list(np.ravel(np.asarray(population)))
    flat_mutants    = list(np.ravel(np.asarray(mutants)))
    both            = zip(flat_population, flat_mutants)
    parity_check    = sum([int(x[0]==x[1]) for x in both])
    if number_of_mutations > 0:
        assert parity_check <= max_parity_sum-rows_algos, 'Error: there should be at least one difference per algo'
    assert parity_check > 0, 'Error: they should not be completely different'
    print('pass')

In [12]:
'''
# vector mutate
'''

def test_vector_mutate():
    number_of_mutations   = get_number_of_mutations()
    population            = build_population()
    mutate_request        = MutateRequest(population)
    mutants               = vector_mutate(mutate_request)
    max_parity_sum        = population.shape[0] * population.shape[1]
    rows_algos            = mutate_request.rows_algos
    
    #form
    assert isinstance(mutants,      np.ndarray),  'Error: should be an np array'
    assert isinstance(mutants[0],   np.ndarray),  'Error: should be an np array'
    assert isinstance(mutants[0][0],np.matrix), 'Error: should be a float'
    
    #content
    flat_population = list(np.ravel(np.asarray(population)))
    flat_mutants    = list(np.ravel(np.asarray(mutants)))
    both            = zip(flat_population, flat_mutants)
    parity_check    = sum([int(x[0]==x[1]) for x in both])
    if number_of_mutations > 0:
        assert parity_check <= max_parity_sum-rows_algos, 'Error: there should be at least one difference per algo'
    assert parity_check > 0, 'Error: they should not be completely different'
    print('pass')

In [13]:
'''
# pygad mutate
'''
    
def test_pygad_mutate():
    number_of_mutations   = get_number_of_mutations()
    population            = build_population()
    mutate_request        = MutateRequest(population)
    mutants               = pygad_mutate(mutate_request)
    max_parity_sum        = population.shape[0] * population.shape[1]
    rows_algos            = mutate_request.rows_algos
    
    #form
    assert isinstance(mutants,      np.ndarray),  'Error: should be an np array'
    assert isinstance(mutants[0],   np.ndarray),  'Error: should be an np array'
    assert isinstance(mutants[0][0],float), 'Error: should be a float'
    
    #content
    flat_population = list(np.ravel(np.asarray(population)))
    flat_mutants    = list(np.ravel(np.asarray(mutants)))
    both            = zip(flat_population, flat_mutants)
    parity_check    = sum([int(x[0]==x[1]) for x in both])
    if number_of_mutations > 0:
        assert parity_check <= max_parity_sum-rows_algos, 'Error: there should be at least one difference per algo'
    assert parity_check > 0, 'Error: they should not be completely different'
    print('pass')
    


In [14]:
'''def test_none_are_same():
    population          = build_population()
    mutate_request      = MutateRequest(population)
    
    number_of_mutations = get_number_of_mutations()
    
    base_mutants        =  base_mutate(mutate_request)
    keith_mutants       = keith_mutate(mutate_request)
    pygad_mutants       = pygad_mutate(mutate_request)
    vector_mutants      = vector_mutate(mutate_request)
    
    if number_of_mutations > 0:
    
        assert  np.asarray(base_mutants).all()     !=  keith_mutants.all(), 'Error: really unlikely, more likely object blurring'
        assert  np.asarray(base_mutants).all()     !=  pygad_mutants.all(), 'Error: really unlikely, more likely object blurring'
        assert  np.asarray(base_mutants).all()     != vector_mutants.all(), 'Error: really unlikely, more likely object blurring'
        assert keith_mutants.all()     !=  pygad_mutants.all(), 'Error: really unlikely, more likely object blurring'
        assert keith_mutants.all()     != vector_mutants.all(), 'Error: really unlikely, more likely object blurring'
        assert pygad_mutants.all()     != vector_mutants.all(), 'Error: really unlikely, more likely object blurring'
        
    if number_of_mutations == 0:
        
        assert  np.asarray(base_mutants).all()     ==  keith_mutants.all(), 'Error: should be same'
        assert  np.asarray(base_mutants).all()     ==  pygad_mutants.all(), 'Error: should be same'
        assert  np.asarray(base_mutants).all()     == vector_mutants.all(), 'Error: should be same'
        assert keith_mutants.all()     ==  pygad_mutants.all(), 'Error: should be same'
        assert keith_mutants.all()     == vector_mutants.all(), 'Error: should be same'
        assert pygad_mutants.all()     == vector_mutants.all(), 'Error: should be same'
'''

"def test_none_are_same():\n    population          = build_population()\n    mutate_request      = MutateRequest(population)\n    \n    number_of_mutations = get_number_of_mutations()\n    \n    base_mutants        =  base_mutate(mutate_request)\n    keith_mutants       = keith_mutate(mutate_request)\n    pygad_mutants       = pygad_mutate(mutate_request)\n    vector_mutants      = vector_mutate(mutate_request)\n    \n    if number_of_mutations > 0:\n    \n        assert  np.asarray(base_mutants).all()     !=  keith_mutants.all(), 'Error: really unlikely, more likely object blurring'\n        assert  np.asarray(base_mutants).all()     !=  pygad_mutants.all(), 'Error: really unlikely, more likely object blurring'\n        assert  np.asarray(base_mutants).all()     != vector_mutants.all(), 'Error: really unlikely, more likely object blurring'\n        assert keith_mutants.all()     !=  pygad_mutants.all(), 'Error: really unlikely, more likely object blurring'\n        assert keith_mutan

In [15]:
 
'''
# tests per se
'''

def tests():
    
    test_base_mutate()
    test_build_population()
    #test_keith_mutate()
    test_pygad_mutate()
    test_vector_mutate()
    print('\nwell done passed all active tests - stick to TDD even where you are excited.\n')
    #test_none_are_same()
    
tests()

pass
pass
pass
pass

well done passed all active tests - stick to TDD even where you are excited.

